### ISSUE TITLE
in the middle of adding a message queue ?

### ISSUE THREAD

**Issue by gedw99** [softashell/comfy-translator#1]
I get :
``` 
./main.go:22:15: undefined: Queue
./main.go:65:6: undefined: NewQueue
./main.go:80:5: undefined: ServeComfyRPC
make: *** [com-build] Error 2
```

**Comment by gedw99** [comment]
I want to add a in process database based on badgerdb, which acts as a queue.

**Comment by gedw99** [comment]
also could you add a template comfy-translator.toml to the repo ?

**Comment by softashell** [comment]
I'm not sure why you're getting that compilation error, but Queue is defined in queue.go and it compiles with no issues for me from current master using  `go version go1.17.3 linux/amd64`
I added the default config [here](https://github.com/softashell/comfy-translator/raw/master/comfy-translator.toml).

**Comment by softashell** [comment]
Actually seems like you're trying to build using ``go build main.go``, doing that reproduces it for me.
To build this all you need to do is:
```
git clone https://github.com/softashell/comfy-translator.git
cd comfy-translator
go build
```
and then you can run it with
`./comfy-translator`

**Comment by gedw99** [comment]
thanks . makes sense.  Will adjust things and try again

**Comment by gedw99** [comment]
yep that fixed everything. thanks
